# Generated by Django 4.2.11 on 2024-05-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenias',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='appMarketing.servicio'),
        ),
    ]
