# Generated by Django 3.2.25 on 2024-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administrador'), (2, 'cliente')], default=2),
        ),
    ]
