# Generated by Django 4.2.11 on 2024-05-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0002_resenias_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenias',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
