# Generated by Django 4.2.11 on 2024-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0003_trabajador_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicio_carrito',
            field=models.ManyToManyField(to='appMarketing.servicio'),
        ),
    ]
