# Generated by Django 4.2.11 on 2024-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0003_alter_resenias_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
