# Generated by Django 4.2.11 on 2024-05-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0004_servicio_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallesCarrito',
            new_name='CarritoUsuario',
        ),
    ]
