# Generated by Django 4.2.11 on 2024-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0004_remove_servicio_pedidos_pedido_servicio_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescarrito',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
