# Generated by Django 4.2.11 on 2024-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0005_alter_detallescarrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
