# Generated by Django 4.2.11 on 2024-05-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0006_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritousuario',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='appMarketing.pedido'),
        ),
    ]
