# Generated by Django 4.2.11 on 2024-05-21 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0007_alter_carritousuario_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
