# Generated by Django 4.2.11 on 2024-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0008_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'trabajador'), (2, 'cliente')], default=2),
        ),
    ]
