# Generated by Django 4.2.11 on 2024-05-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0009_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMarketing.cliente'),
        ),
        migrations.AlterField(
            model_name='resenias',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMarketing.cliente'),
        ),
    ]
